### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by confususs** [pytest-dev/pytest-flask#72]
I'm running into this warning for my tests:

```
~/.virtualenvs/api/lib/python2.7/site-packages/pytest_flask/plugin.py:109: DeprecationWarning: use of getfuncargvalue is deprecated, use getfixturevalue
    app = request.getfuncargvalue('app')
```

I see that the deprecation is fixed in https://github.com/pytest-dev/pytest-flask/commit/8aba5e0be8db1b2a1431414f186e263e121582dc, but there was not yet a release after this fix. Could you provide one? Thanks!

**Comment by Jitsusama** [comment]
Yeah; a lack of a new release in over 2 years makes me nervous to use this library, particularly when there are open pull requests and issues.

**Comment by nicoddemus** [comment]
Any news from @vitalk, @steenzout, or other contributors? Indeed has been awhile since the last release. 

It is also possible to consider bringing in more contributors to the project if the current contributors don't have time anymore to work on it, which happens sometimes (people might move jobs and not even use Python anymore for example) and this is perfectly OK.

**Comment by steenzout** [comment]
I can't merge requests so there is nothing I can do anyway besides forking the repo and going solo.

**Comment by nicoddemus** [comment]
Oh sorry I thought you had write access here, my bad.

Let's avoid forking, let's wait for feedback from @vitalk.

**Comment by nicoddemus** [comment]
Opened #76 to discuss this issue.

**Comment by nicoddemus** [comment]
Hi everyone, `0.11` has finally been released! 🎉
