### ISSUE TITLE
Plugin does not loaded

### ISSUE THREAD

**Issue by vitalk** [pytest-dev/pytest-flask#9]
Re https://github.com/vitalk/pytest-flask/issues/7#issuecomment-60576004

Looks like a `pytest-flask` not loaded at all:

`available fixtures: pytestconfig, app, recwarn, monkeypatch, capfd, capsys, tmpdir`

Can you provide a head of your `pytest` stack trace? The list of loaded
plugins shows at the top, for example:

``` bash
$ py.test tests/
test session starts
platform darwin -- Python 2.7.8 -- py-1.4.24 -- pytest-2.6.2
plugins: flask
collected 443 items

...
```

/cc @bonya

**Comment by evadeflow** [comment]
Here's a _possibly_ relevant anecdote: I was getting exactly the `fixture 'client' not found` error described in this issue, even though `pytest-flask` was already installed. On a random hunch, I ran `pip install ipython` and—after doing that—the pytest-flask plugin loaded fine. Not that I'm suggesting that installing `ipython` is a proper 'fix' for this. But perhaps it provides a clue as to the root cause.

**Comment by vitalk** [comment]
Thanks @evadeflow for a note. But this looks a little bit strange for me. Do you update your python/pytest environment at first, as [mentioned before](https://github.com/vitalk/pytest-flask/issues/9#issuecomment-60585469)?

**Comment by kabapy** [comment]
add the required fixture
`
@pytest.fixture
def client():
    app = create_app()
    client = app.test_client()
    return client
`

**Comment by senaps** [comment]
@kabapy if i do so, then i'll get an error telling me url_for needs to be ran with a context-manager.

i have the same issue of not being able to find client fixture.

**Comment by senaps** [comment]
i was able to pass the test's by removing pytest, pytest-flask and installing them again.

**Comment by kabapy** [comment]
I avoid flask-pytest and use pytest directly
